# Generated by Django 4.2.6 on 2023-10-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('reservation_date', models.DateField()),
                ('reservation_slot', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('reservation_date', 'reservation_slot')},
            },
        ),
    ]
